version: "3.4"

services:
  backend:
    container_name: tri-backend
    image: vcheeney/tri-backend
    build: ./backend
    environment:
      - BACKEND_PORT
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@tri-database:5432/${POSTGRES_DB}?schema=public
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
