version: "3.4"

services:
  backend:
    container_name: tri-backend
    image: vcheeney/tri-backend
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@tri-database:5432/mydb?schema=public
    ports:
      - "3000:3000"
