version: "3.4"

services:
  frontend:
    container_name: tri-frontend
    image: vcheeney/tri-frontend
    build: ./frontend
    environment:
      - FRONTEND_PORT
      - VITE_API_BASE_PATH=http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
