version: "3.4"

services:
  database:
    image: postgres
    container_name: tri-database
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
