version: "3.4"

services:
  database:
    image: postgres
    container_name: tri-database
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
